<?php

return [

    'FIREBASE_API_KEY' => env('FIREBASE_API_KEY', ''),
    'FIREBASE_AUTH_DOMAIN' => env('FIREBASE_AUTH_DOMAIN', ''),
    'FIREBASE_PROJECT_ID' => env('FIREBASE_PROJECT_ID', ''),
    'FIREBASE_STORAGE' => env('FIREBASE_STORAGE', ''),
    'FIREBASE_MESSAGER_SENDER_ID' => env('FIREBASE_MESSAGER_SENDER_ID'),
    'FIREBASE_APP_ID' => env('FIREBASE_APP_ID', ''),
    'FIREBASE_MEASUREMENT_ID' => env('FIREBASE_MEASUREMENT_ID', ''),

];
